### ISSUE TITLE
Questions about the data

### ISSUE THREAD

**Issue by lizixiaoboluo** [XiangyangLi20/KERM#1]
Thank you for your excellent work! I‘m interesting in constructing knowledge base.How do you construct the knowledge base? For example, ”light hanging over kitchen island“. Thank you for your patience.

**Comment by MrZihan** [comment]
As described in our paper, ”Specifically, in the Visual Genome dataset, the parsed attribute annotations take the form of “attribute-object” pairs and the parsed relationship annotations take the form of “subject-predicate-object” triplets. We convert all of the “attribute-object” pairs and “subject-predicate-object” triplets to their synset canonical forms. “  Simply put, we collected the annotations on the Visual Genome dataset and converted them into phrases. For example, the annotation "light-hanging over-kitchen island"(i.e., subject-predicate-object) can be converted into the "light hanging over kitchen island". The code is in `preprocess/get_knowledge_base.py`.

**Comment by lizixiaoboluo** [comment]
I see，Thank you again for your patient answer！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiangyangLi20/KERM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月15日(星期一) 下午4:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiangyangLi20/KERM] Questions about the data (Issue #1)





 
As described in our paper, ”Specifically, in the Visual Genome dataset, the parsed attribute annotations take the form of “attribute-object” pairs and the parsed relationship annotations take the form of “subject-predicate-object” triplets. We convert all of the “attribute-object” pairs and “subject-predicate-object” triplets to their synset canonical forms. “  Simply put, we collected the annotations on the Visual Genome dataset and converted them into phrases. For example, the annotation "light-hanging over-kitchen island"(i.e., subject-predicate-object) can be converted into the "light hanging over kitchen island". The code is in preprocess/get_knowledge_base.py.
