### ISSUE TITLE
Questions about the experimental results

### ISSUE THREAD

**Issue by ghost** [XiangyangLi20/KERM#3]
Hi, thanks for your great work! 
When tried to run the experiment on REVERIE, I found it hard to achieve the performance mentioned in the paper.
I fine-tuned the pre-trained model with batch_size of 2 for 20k iterations on 4 V100 GPUs, the best results of the Val_Unseen dataset are SR:42.40, SPL:29.14, RGS: 27.78 and RGSPL: 19.66 (achieved at 2000 iterations).
I wonder if it’s due to the difference in the pre-trained model. Could you please provide your pre-trained model and more details about the training procedure? 
Thanks!

**Comment by MrZihan** [comment]
Thanks for your interest in our work.
If you use DUET's pre-trained model and then fine-tune it with KERM's code, there will be a sharp drop in performance because the newly added parameters in KERM are randomly initialized. A recommended strategy is to freeze the model parameters of DUET and train only the newly added parameters of KERM. After the training of the new parameters is completed, fine-tune them together.

**Comment by ghost** [comment]
> Thanks for your interest in our work. If you use DUET's pre-trained model and then fine-tune it with KERM's code, there will be a sharp drop in performance because the newly added parameters in KERM are randomly initialized. A recommended strategy is to freeze the model parameters of DUET and train only the newly added parameters of KERM. After the training of the new parameters is completed, fine-tune them together.

Thanks for your in-time and patient reply. 
I used KERM’s pre-train code(`pretrain_src`) to pre-train the model from scratch, not DUET’s code or DUET’s pre-trained model.
Do you mean that I need to use the pre-trained DUET model as initialization and freeze the DUET’s parameters while running KERM‘s pre-training? and After KERM’s pre-training, run KERM’s fine-tuning code to finetune all the parameters ?

**Comment by violet-ship** [comment]
@MrZihan 
Hello, could you elaborate on your GPU specifications? I have 4 V100s, with a memory size of 116GB and a CPU with 36 cores. There was an issue with the image during pre-training.

![Image](https://github.com/user-attachments/assets/f7341ef7-8f7f-4661-a115-d5119e7e59be)
